### ISSUE TITLE
Can't find FC

### ISSUE THREAD

**Issue by Lisertan** [WesselKuipers/FCNameColor#12]
Heya,

whatever I do, the Plugin can't find my FC and therefore won't work. I disabled/enabled it several times over several days. No change. 

I do know that my Character is in the Lodestone twice for some reason. A lvl 1 version and my current character (any yes, same name and it's both me... I think the lvl 1 version was my beta char or something). So I guess it's trying to get the data from the lvl 1 version that has no FC and never will have one as the char does not exist.

Any idea what I could do?

**Comment by joshuahiskraken** [comment]
[ERR] [FCNameColor] Could not find player on Lodestone

**Comment by WesselKuipers** [comment]
> [ERR] [FCNameColor] Could not find player on Lodestone https://na.finalfantasyxiv.com/lodestone/character/29916559/
> 
> Char is on lodestone. Not sure how to get around this issue. It used to work fine back in SB

I just checked on Lodestone by searching for your character's name and I think what's going on here is that the way Netstone is inserting the character name without quotes, which does a loose search instead of trying to find an exact match, see the difference between [this search result](https://na.finalfantasyxiv.com/lodestone/character/?q=Risa+Risa&worldname=Jenova&classjob=&race_tribe=&blog_lang=ja&blog_lang=en&blog_lang=de&blog_lang=fr&order=) where you end up on page 4, and [this search result](https://na.finalfantasyxiv.com/lodestone/character/?q=%22Risa+Risa%22&worldname=Jenova&classjob=&race_tribe=&blog_lang=ja&blog_lang=en&blog_lang=de&blog_lang=fr&order=) where I wrapped your character's name in quotes. 

Previously the plugin used XIVApi to fetch your character, but since they're moving away from parsing Lodestone this way I ended up using Netstone as a replacement, which does the same thing but locally.

Looking at the source code for Netstone, it seems that [by default it doesn't wrap quotes around the character name when searching](https://github.com/xivapi/NetStone/blob/master/NetStone/Search/Character/CharacterSearchQuery.cs#L47), but it should be easy enough to fix on my end.

My sub ran out recently so I can't test this properly right now but I can make a test version of the plugin that makes this change.

**Comment by WesselKuipers** [comment]
@Lisertan 
> Heya,
> 
> whatever I do, the Plugin can't find my FC and therefore won't work. I disabled/enabled it several times over several days. No change.
> 
> I do know that my Character is in the Lodestone twice for some reason. A lvl 1 version and my current character (any yes, same name and it's both me... I think the lvl 1 version was my beta char or something). So I guess it's trying to get the data from the lvl 1 version that has no FC and never will have one as the char does not exist.
> 
> Any idea what I could do?

What's your character's name and server?

**Comment by Lisertan** [comment]
> @Lisertan
> 
> > Heya,
> > whatever I do, the Plugin can't find my FC and therefore won't work. I disabled/enabled it several times over several days. No change.
> > I do know that my Character is in the Lodestone twice for some reason. A lvl 1 version and my current character (any yes, same name and it's both me... I think the lvl 1 version was my beta char or something). So I guess it's trying to get the data from the lvl 1 version that has no FC and never will have one as the char does not exist.
> > Any idea what I could do?
> 
> What's your character's name and server?

Hi, I'M Selandrea Macmardigan on Shiva 

Lodestone: https://de.finalfantasyxiv.com/lodestone/character/?q=Selandrea&worldname=Shiva&classjob=&race_tribe=&blog_lang=ja&blog_lang=en&blog_lang=de&blog_lang=fr&order=

(I'm the one that's not lvl 1 lol)

Thank you for your help :)

**Comment by joshuahiskraken** [comment]
@WesselKuipers If you want, I could test it for you. Just let me know when the test version is up and I'll install.

**Comment by joshuahiskraken** [comment]
And thanks for the work you've put in to make this plugin. We all really appreciate it!

**Comment by WesselKuipers** [comment]
@joshuahiskraken I've just pushed version `2.0.3.4` as a test plugin, 

If you don't know how to install testing plugins:
1. Type `/xlsettings` in game.
2. Go to the `Experimental` tab
3. Click the checkbox for `Get plugin testing builds`
4. Save / Save and Close

**Comment by WesselKuipers** [comment]
@Lisertan That's super weird! I'm surprised SE isn't purging characters like this. Unfortunately I couldn't figure out a good way to fix this, I think one solution might be to allow users to enter their character's ID from Lodestone manually for issues like this, which would require a bit more time on my end to properly implement.

In the meantime you can fix the issue by manually changing the settings that are saved by the plugin:
1. Navigate to `%appdata%/XIVLauncher/pluginConfigs`
2. Open up `FCNameColor.json` in your preferred text editor
3. Under `PlayerIDs`, there should be an entry there that looks like this:
```json
  "PlayerIDs": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.String, System.Private.CoreLib]], System.Private.CoreLib",
    "Selandrea Macmardigan@Shiva": "2679915"
  },
```
4. Change the ID stored there to the ID of your actual character: `2206799`
5. Reload FCNameColor by restarting the game or by manually disabling and re-enabling the plugin

Character IDs are stored by FCNameColor in order to not hit Lodestone for information that's normally not going to change, so this way it'll use the correct ID when updating the list of FC members.

Note that if you hit the reset button you'll have to go through these steps again since this clears out all the stored IDs.

**Comment by Lisertan** [comment]
> @Lisertan That's super weird! I'm surprised SE isn't purging characters like this. Unfortunately I couldn't figure out a good way to fix this, I think one solution might be to allow users to enter their character's ID from Lodestone manually for issues like this, which would require a bit more time on my end to properly implement.
> 
> In the meantime you can fix the issue by manually changing the settings that are saved by the plugin:
> 
>     1. Navigate to `%appdata%/XIVLauncher/pluginConfigs`
> 
>     2. Open up `FCNameColor.json` in your preferred text editor
> 
>     3. Under `PlayerIDs`, there should be an entry there that looks like this:
> 
> 
> ```json
>   "PlayerIDs": {
>     "$type": "System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.String, System.Private.CoreLib]], System.Private.CoreLib",
>     "Selandrea Macmardigan@Shiva": "2679915"
>   },
> ```
> 
>     4. Change the ID stored there to the ID of your actual character: `2206799`
> 
>     5. Reload FCNameColor by restarting the game or by manually disabling and re-enabling the plugin
> 
> 
> Character IDs are stored by FCNameColor in order to not hit Lodestone for information that's normally not going to change, so this way it'll use the correct ID when updating the list of FC members.
> 
> Note that if you hit the reset button you'll have to go through these steps again since this clears out all the stored IDs.

Legend! Works like a charm. Thank you so much.

**Comment by joshuahiskraken** [comment]
@WesselKuipers Excellent! Its working perfectly now.
