### ISSUE TITLE
Addon is being overriden by SimpleTweaks

### ISSUE THREAD

**Issue by darknite323** [WesselKuipers/FCNameColor#18]
This Only started happening on the new update 2.1.0.4 
Trying to use the Simple tweaks setting "Custom Free Company Tags", to recolour the FC tag for all players "Default FC", then overrides any colours set in FCNameColor.

![image](https://user-images.githubusercontent.com/49840343/166132987-4e278c3e-d1cc-4b1d-b1c3-76a93ea2dc1e.png)

**Comment by WesselKuipers** [comment]
With 2.1.0.4 I made some changes in order to make the plugin more compatible with other plugins that change the nameplate colour, which also changed this specific interaction seemingly.

To attempt to fix this I tried out changing the load order of my plugin vs SimpleTweaks so it loads later and thus processes the nameplate later giving it higher priority when processing the nameplates, but that doesn't seem to make a difference.

I'll discuss a potential fix with Caraxi later, for now a workaround would be to include your additional FCs in the list of custom FC tags for the Tweak, which would be the same but without the colour override:
![image](https://user-images.githubusercontent.com/4731930/166164313-0f32aa3a-1c55-4858-b575-4ef183093397.png)

Any other change like icons or custom text or italics, etc, will work without issue now whereas before it wouldn't do anything with those.
