### ISSUE TITLE
[BUG] Not Updating FC nameplate

### ISSUE THREAD

**Issue by werewolfboy13** [WesselKuipers/FCNameColor#31]
After the net code bump I am noticing that FC tags are not updating. If any logs are needed please let me know. 

![image](https://user-images.githubusercontent.com/43587009/213819462-600d0f69-c5ee-432f-aca8-f356f611617e.png)

**Comment by SongenCarpincha** [comment]
I have the same issue, so uninstalled it, deleted the folder and reinstalled again, what a mistake... now im stucked at the first setup prompt since 3 weeks.
![image](https://user-images.githubusercontent.com/110448057/219620192-1ce8ebfd-436f-4ff1-8cb7-030b622cf005.png)
![image](https://user-images.githubusercontent.com/110448057/219620271-ab27fec9-5e46-4489-b124-30498a02f38c.png)

**Comment by WesselKuipers** [comment]
Could you provide some logs? I can't tell based on this what might be going wrong.

I'm currently kinda burned out on FFXIV and I don't really have much spare time currently due to irl issues, but maybe we can figure things out.

**Comment by WesselKuipers** [comment]
I've gone ahead and made a new testing version (version `3.0.2.0`) which may very well help with this issue.
@werewolfboy13 @SongenCarpincha Could you try this version and see if it fixes the problems you're having?

If you right click on the plugin in the plugin list you should get an option to receive test versions of the plugin.

**Comment by werewolfboy13** [comment]
I will take a look when I am able.

**Comment by werewolfboy13** [comment]
Appears to be fixed.


![image](https://user-images.githubusercontent.com/43587009/221380709-6b7c092d-0b02-4549-b08a-f6ac68bbd92f.png)

**Comment by WesselKuipers** [comment]
Nice! Closing for now, if something else pops up feel free to create a new issue.
