### ISSUE TITLE
7.0 Update?

### ISSUE THREAD

**Issue by Frost212** [WesselKuipers/FCNameColor#48]
I know it's still early, and i don't expect you to already have this updated. But given that the last time it broke it took a while to fix, i can't help but wonder. Will this eventually be updated for 7.0? Or should we consider this abandoned. Thanks!

**Comment by WesselKuipers** [comment]
I'm still in the middle of completing the MSQ, but after that there's still some research that needs to be done on handling nameplates since those seem to have changed quite a bit in Dawntrail.

There are plans on having nameplates included as an API for developers to use directly from Dalamud which means they'll be updated way sooner in future by people smarter than me, allowing me to update the plugin much quicker.

Once we know more about how to handle nameplates I can work on updating this, but I don't have an ETA on that yet.

**Comment by Frost212** [comment]
No worries, thank you for the speedy reply and enjoy the rest of your MSQ!

**Comment by WesselKuipers** [comment]
Quick update: I'm working on updating it now. It also turns out it's possible to do any arbitrary RGB value for colours so I'm probably throwing away the colour palette thing and replacing it with a colour picker instead, as well as reworking some of the existing UI stuff. 

I'm not sure how fast I'll finish all of the UI rework stuff but expect an update sometime this weekend!

**Comment by WesselKuipers** [comment]
Work in progress can be found here :)
https://github.com/WesselKuipers/FCNameColor/pull/49

**Comment by WesselKuipers** [comment]
Version 5.0.0.0 is out now!
